from django.urls import path
from . import views

urlpatterns = [
    path('csrf/', views.csrf_cookie),
    path('signup/', views.signup),
    path('login/', views.login_user),
    path('logout/', views.logout_user),
    path('token/refresh/', views.custom_token_refresh),
    path('forgot-password/', views.forgot_password),
    path('reset-password/', views.reset_password),
    path('start-session/', views.start_session),
    path('pause-session/', views.pause_session),
    path('resume-session/', views.resume_session),
    path('end-session/', views.end_session),
    path('sessions/', views.get_sessions),
    path('stats/', views.get_stats),
    path('insights/', views.get_insights),
    path('productivity-score/', views.get_productivity_score),
    path('heatmap/', views.get_heatmap),
    path('save-preset/', views.save_preset),
    path('presets/', views.presets_collection),
    path('presets/<int:id>/', views.delete_preset_by_id),
    path('delete-preset/<int:id>/', views.delete_preset),
    path('music/upload/', views.upload_music),
    path('music/tracks/', views.list_music_tracks),
    path('music/playlists/', views.playlists_collection),
    path('music/playlists/<int:id>/', views.playlist_detail),
    path('music/favorites/', views.favorites_collection),
    path('music/favorites/add/', views.add_favorite),
    path('music/favorites/remove/', views.remove_favorite),
    path('music/queue/', views.get_queue),
    path('music/queue/add/', views.add_to_queue),
    path('music/queue/remove/', views.remove_from_queue),
    path('music/queue/reorder/', views.reorder_queue),
    path('music/queue/next/', views.play_next),
    path('music/queue/previous/', views.play_previous),
    path('music/queue/shuffle/', views.toggle_shuffle),
    path('music/queue/repeat/', views.set_repeat),
    path('music/queue/state/', views.playback_state),
    # Admin management
    path('admin/users/', views.admin_list_users),
    path('admin/users/count/', views.admin_user_count),
    path('admin/users/<int:user_id>/', views.admin_delete_user),
]
