# Generated by Django 6.0.3 on 2026-04-07 05:29

from django.db import migrations, models


def deduplicate_preset_names(apps, schema_editor):
    Preset = apps.get_model("focusapp", "Preset")
    seen_names = {}

    for preset in Preset.objects.all().order_by("id"):
        count = seen_names.get(preset.name, 0)
        if count == 0:
            seen_names[preset.name] = 1
            continue

        base_name = preset.name
        suffix = count + 1
        new_name = f"{base_name} ({suffix})"
        while Preset.objects.filter(name=new_name).exists():
            suffix += 1
            new_name = f"{base_name} ({suffix})"

        preset.name = new_name
        preset.save(update_fields=["name"])
        seen_names[base_name] = suffix


class Migration(migrations.Migration):

    dependencies = [
        ('focusapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preset',
            options={'ordering': ['name', 'id']},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.RunPython(deduplicate_preset_names, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='preset',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
