# Generated by Django 6.0.3 on 2026-04-08 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_session_state(apps, schema_editor):
    Session = apps.get_model("focusapp", "Session")
    Session.objects.filter(completed=True).update(status="completed")


class Migration(migrations.Migration):

    dependencies = [
        ('focusapp', '0002_alter_preset_options_alter_session_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed')], default='running', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='total_sessions',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='session',
            name='current_session',
            field=models.IntegerField(default=1),
        ),
        migrations.RunPython(backfill_session_state, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='session',
            name='completed',
        ),
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('signup', 'Signup'), ('login', 'Login')], max_length=20)),
                ('code', models.CharField(max_length=6)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
