# Generated by Django 6.0.3 on 2026-04-08 12:06

from django.db import migrations, models


def add_completed_column_if_missing(apps, schema_editor):
    connection = schema_editor.connection
    table_name = "focusapp_session"

    with connection.cursor() as cursor:
        existing_columns = {
            column.name for column in connection.introspection.get_table_description(cursor, table_name)
        }

        if "completed" not in existing_columns:
            schema_editor.execute(
                "ALTER TABLE focusapp_session ADD COLUMN completed boolean NOT NULL DEFAULT FALSE"
            )


class Migration(migrations.Migration):

    dependencies = [
        ('focusapp', '0004_repair_session_counters'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    add_completed_column_if_missing,
                    migrations.RunPython.noop,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='session',
                    name='completed',
                    field=models.BooleanField(default=False),
                ),
            ],
        ),
    ]
