# Generated by Django 6.0.3 on 2026-04-26 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focusapp', '0005_session_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='code',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='purpose',
            field=models.CharField(choices=[('signup', 'Signup'), ('login', 'Login'), ('reset', 'Reset')], max_length=20),
        ),
    ]
