# Generated by Django 6.0.3 on 2026-04-26 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('focusapp', '0006_alter_otpverification_code_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTPVerification',
        ),
    ]
