# Generated by Django 6.0.3 on 2026-07-04 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def delete_unowned_data(apps, schema_editor):
    Session = apps.get_model('focusapp', 'Session')
    Preset = apps.get_model('focusapp', 'Preset')
    Session.objects.all().delete()
    Preset.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('focusapp', '0010_session_pause_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='preset',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='session',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(delete_unowned_data),
        migrations.AlterField(
            model_name='preset',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='preset',
            unique_together={('user', 'name')},
        ),
    ]

