# Generated by Django 6.0.3 on 2026-07-05 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focusapp', '0011_preset_user_session_user_alter_preset_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='timer_type',
            field=models.CharField(default='default', max_length=20),
        ),
    ]
